<br>

####   hw6pr1iris_modeler 
+ iris clasification and regression via NNets


In [1]:
#
# hw6pr1iris_modeler:  NNETS! 
#
#   including _both_ clasification + regression for iris-species modeling
#

In [2]:
# libraries...
import numpy as np      # numpy is Python's "array" library
import pandas as pd     # Pandas is Python's "data" library ("dataframe" == spreadsheet)

In [4]:
# let's read in our flower data...
# 
# iris_cleaned.csv and hw4pr1iris_cleaner.ipynb should be in this folder
# 
filename = 'iris_cleaned.csv'
df_tidy = pd.read_csv(filename)      # encoding = "utf-8", "latin1"
print(f"{filename} : file read into a pandas dataframe.")

iris_cleaned.csv : file read into a pandas dataframe.


In [5]:
#
# different version vary on how to see all rows (adapt to suit your system!)
#
print(f"df_tidy.shape is {df_tidy.shape}\n")
df_tidy.info()  # prints column information

# let's print the whole dataframe, too  (adapt # of lines, as desired)
# pd.options.display.max_rows = 150   # None for no limit; default: 10
# pd.options.display.min_rows = 150   # None for no limit; default: 10
# pd.options.display.max_rows = 10   # None for no limit; default: 10
# pd.options.display.min_rows = 10   # None for no limit; default: 10
df_tidy

df_tidy.shape is (141, 6)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 141 entries, 0 to 140
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   sepallen  141 non-null    float64
 1   sepalwid  141 non-null    float64
 2   petallen  141 non-null    float64
 3   petalwid  141 non-null    float64
 4   irisname  141 non-null    object 
 5   irisnum   141 non-null    int64  
dtypes: float64(4), int64(1), object(1)
memory usage: 7.7+ KB


sepallen  sepalwid  petallen  petalwid   irisname  irisnum
0         4.6       3.6       1.0       0.2     setosa        0
1         4.3       3.0       1.1       0.1     setosa        0
2         5.0       3.2       1.2       0.2     setosa        0
3         5.8       4.0       1.2       0.2     setosa        0
4         4.4       3.0       1.3       0.2     setosa        0
..        ...       ...       ...       ...        ...      ...
136       7.9       3.8       6.4       2.0  virginica        2
137       7.6       3.0       6.6       2.1  virginica        2
138       7.7       3.8       6.7       2.2  virginica        2
139       7.7       2.8       6.7       2.0  virginica        2
140       7.7       2.6       6.9       2.3  virginica        2

[141 rows x 6 columns]

In [6]:
#
# All of the columns need to be numeric, we'll drop irisname
ROW = 0
COLUMN = 1
df_model1 = df_tidy.drop( 'irisname', axis=COLUMN )
df_model1

sepallen  sepalwid  petallen  petalwid  irisnum
0         4.6       3.6       1.0       0.2        0
1         4.3       3.0       1.1       0.1        0
2         5.0       3.2       1.2       0.2        0
3         5.8       4.0       1.2       0.2        0
4         4.4       3.0       1.3       0.2        0
..        ...       ...       ...       ...      ...
136       7.9       3.8       6.4       2.0        2
137       7.6       3.0       6.6       2.1        2
138       7.7       3.8       6.7       2.2        2
139       7.7       2.8       6.7       2.0        2
140       7.7       2.6       6.9       2.3        2

[141 rows x 5 columns]

In [7]:
#
# once we have all the columns we want, let's create an index of their names...

#
# Let's make sure we have all of our helpful variables in one place 
#       To be adapted if we drop/add more columns...
#

#
# let's keep our column names in variables, for reference
#
COLUMNS = df_model1.columns            # "list" of columns
print(f"COLUMNS is {COLUMNS}\n")  
  # It's a "pandas" list, called an Index
  # use it just as a Python list of strings:
print(f"COLUMNS[0] is {COLUMNS[0]}\n")

# let's create a dictionary to look up any column index by name
COL_INDEX = {}
for i, name in enumerate(COLUMNS):
    COL_INDEX[name] = i  # using the name (as key), look up the value (i)
print(f"COL_INDEX is {COL_INDEX}\n\n")


#
# and our "species" names
#

# all of scikit-learn's ML routines need numbers, not strings
#   ... even for categories/classifications (like species!)
#   so, we will convert the flower-species to numbers:

SPECIES = ['setosa','versicolor','virginica']   # int to str
SPECIES_INDEX = {'setosa':0,'versicolor':1,'virginica':2}  # str to int

# Let's try it out...
for name in SPECIES:
    print(f"{name} maps to {SPECIES_INDEX[name]}")

COLUMNS is Index(['sepallen', 'sepalwid', 'petallen', 'petalwid', 'irisnum'], dtype='object')

COLUMNS[0] is sepallen

COL_INDEX is {'sepallen': 0, 'sepalwid': 1, 'petallen': 2, 'petalwid': 3, 'irisnum': 4}


setosa maps to 0
versicolor maps to 1
virginica maps to 2


In [8]:
#
# let's convert our dataframe to a numpy array, named A
#
A = df_model1.to_numpy()   
A = A.astype('float64')    # many types:  www.tutorialspoint.com/numpy/numpy_data_types.htm
print(A)

[[4.6 3.6 1.  0.2 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [4.6 3.2 1.4 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.8 3.  1.4 0.3 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.  3.3 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.3 3.7 1.5 0.2 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.  3.5 1.6 0.6 0. ]
 [5.1 3.8 1.6 0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [5.4 3.4 1

In [9]:
#
# nice to have NUM_ROWS and NUM_COLS around
#
NUM_ROWS, NUM_COLS = A.shape
print(f"\nThe dataset has {NUM_ROWS} rows and {NUM_COLS} cols")


The dataset has 141 rows and 5 cols


In [12]:
# let's use all of our variables, to reinforce that we have
# (1) names...
# (2) access and control...

# choose a row index, n:
n = 42
print(f"flower #{n} is {A[n]}")

for i in range(len(COLUMNS)):
    colname = COLUMNS[i]
    value = A[n][i]
    print(f"  Its {colname} is {value}")

species_index = COL_INDEX['irisnum']
species_num = int(round(A[n][species_index]))
species = SPECIES[species_num]
print(f"  Its species is {species} (i.e., {species_num})")

flower #42 is [5.4 3.9 1.7 0.4 0. ]
  Its sepallen is 5.4
  Its sepalwid is 3.9
  Its petallen is 1.7
  Its petalwid is 0.4
  Its irisnum is 0.0
  Its species is setosa (i.e., 0)


In [13]:
print("+++ Start of data definitions +++\n")

#
# we could do this at the data-frame level, too!
#

X_all = A[:,0:4]  # X (features) ... is all rows, columns 0, 1, 2, 3
y_all = A[:,4]    # y (labels) ... is all rows, column 4 only

print(f"y_all (just the labels/species)   are \n {y_all}")
print(f"X_all (just the features, first few rows) are \n {X_all[0:5]}")

+++ Start of data definitions +++

y_all (just the labels/species)   are 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
X_all (just the features, first few rows) are 
 [[4.6 3.6 1.  0.2]
 [4.3 3.  1.1 0.1]
 [5.  3.2 1.2 0.2]
 [5.8 4.  1.2 0.2]
 [4.4 3.  1.3 0.2]]


In [14]:
#
# we can scramble the data, to remove (potential) dependence on its ordering: 
# 
indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_all = X_all[indices]              # we apply the _same_ permutation to each!
y_all = y_all[indices]              # again...
print(f"The scrambled labels/species are \n {y_all}")
print(f"The corresponding data rows are \n {X_all[0:5]}")

The scrambled labels/species are 
 [2. 2. 2. 1. 0. 2. 2. 0. 0. 1. 1. 2. 0. 2. 2. 0. 2. 2. 2. 2. 1. 1. 0. 0.
 1. 2. 2. 0. 1. 0. 0. 1. 0. 1. 2. 1. 2. 1. 2. 0. 0. 2. 1. 2. 1. 1. 2. 2.
 2. 1. 2. 2. 1. 2. 2. 1. 1. 1. 2. 0. 0. 1. 0. 2. 2. 1. 2. 1. 0. 0. 2. 0.
 0. 1. 0. 2. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 2. 2. 1. 1. 1. 0. 0. 0. 1.
 2. 1. 1. 2. 0. 2. 0. 0. 1. 0. 2. 0. 2. 0. 1. 0. 1. 1. 0. 0. 0. 1. 2. 2.
 2. 1. 2. 2. 0. 1. 1. 0. 2. 0. 1. 1. 0. 0. 2. 1. 1. 0. 1. 2. 2.]
The corresponding data rows are 
 [[6.4 2.7 5.3 1.9]
 [7.7 2.8 6.7 2. ]
 [6.4 2.8 5.6 2.2]
 [5.5 2.5 4.  1.3]
 [4.8 3.4 1.9 0.2]]


In [15]:
#
# We next separate into test data and training data ... 
#    + We will train on the training data...
#    + We will _not_ look at the testing data to build the model
#
# Then, afterward, we will test on the testing data -- and see how well we do!
#

#
# a common convention:  train on 80%, test on 20%    Let's define the TEST_PERCENT
#

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2)

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows\n" )

print(f"Held-out data... (testing data: {len(y_test)})")
print(f"y_test: {y_test}\n")
print(f"X_test (few rows): {X_test[0:5,:]}")  # 5 rows
print()
print(f"Data used for modeling... (training data: {len(y_train)})")
print(f"y_train: {y_train}\n")
print(f"X_train (few rows): {X_train[0:5,:]}")  # 5 rows

training with 112 rows;  testing with 29 rows

Held-out data... (testing data: 29)
y_test: [0. 1. 0. 2. 1. 2. 1. 0. 0. 1. 1. 1. 1. 2. 1. 0. 2. 1. 0. 0. 0. 0. 1. 2.
 2. 1. 2. 1. 0.]

X_test (few rows): [[5.  3.4 1.6 0.4]
 [5.6 3.  4.5 1.5]
 [5.1 3.8 1.9 0.4]
 [6.1 3.  4.9 1.8]
 [5.5 2.6 4.4 1.2]]

Data used for modeling... (training data: 112)
y_train: [0. 0. 0. 2. 0. 0. 2. 0. 1. 1. 1. 1. 0. 2. 2. 2. 0. 2. 2. 0. 1. 1. 2. 2.
 2. 0. 0. 0. 0. 0. 0. 2. 0. 1. 2. 0. 2. 1. 0. 2. 2. 2. 2. 1. 0. 1. 1. 2.
 1. 0. 0. 1. 2. 1. 1. 2. 0. 0. 0. 1. 2. 2. 2. 2. 2. 2. 1. 0. 0. 1. 1. 1.
 1. 2. 0. 2. 0. 1. 1. 0. 2. 2. 2. 2. 1. 2. 0. 1. 0. 1. 0. 0. 1. 2. 0. 1.
 2. 2. 1. 2. 2. 1. 0. 1. 0. 2. 1. 1. 1. 2. 0. 2.]

X_train (few rows): [[5.1 3.5 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.8 3.  1.4 0.1]
 [6.4 2.8 5.6 2.2]
 [5.  3.4 1.5 0.2]]


In [16]:
#
# for NNets, it's important to keep the feature values near 0, say -1. to 1. or so
#    This is done through the "StandardScaler" in scikit-learn
# 
from sklearn.preprocessing import StandardScaler

USE_SCALER = True   # this variable is important! It tracks if we need to use the scaler...

# we "train the scaler"  (computes the mean and standard deviation)
if USE_SCALER == True:
    scaler = StandardScaler()
    scaler.fit(X_train)  # Scale with the training data! ave becomes 0; stdev becomes 1
else:
    # this one does no scaling!  We still create it to be consistent:
    scaler = StandardScaler(copy=True, with_mean=False, with_std=False) # no scaling
    scaler.fit(X_train)  # still need to fit, though it does not change...

scaler   # is now defined and ready to use...

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Here are our scaled training and testing sets:

X_train_scaled = scaler.transform(X_train) # scale!
X_test_scaled = scaler.transform(X_test) # scale!

y_train_scaled = y_train  # the predicted/desired labels are not scaled
y_test_scaled = y_test  # not using the scaler



In [17]:
#
# let's create a table for showing our data and its predictions...
#
def ascii_table(X,y,scaler_to_invert=None):
    """ print a table of binary inputs and outputs """
    if scaler_to_invert == None:  # don't use the scaler
        X = X
    else:
        X = scaler_to_invert.inverse_transform(X)
    print(f"{'input ':>58s} -> {'pred':<5s} {'des.':<5s}") 
    for i in range(len(y)):
        print(f"{X[i,0:4]!s:>58s} -> {'?':<5s} {y[i]:<5.2f}")   # !s is str ...
    print()
    
# to show the table with the scaled data:
ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],None)

# to show the table with the original data:
ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],scaler)

                                                    input  -> pred  des. 
         [-0.89971416  1.02968317 -1.32964419 -1.32421551] -> ?     0.00 
         [-1.71423599  0.3499709  -1.38500484 -1.32421551] -> ?     0.00 
         [-1.24879494 -0.10317061 -1.32964419 -1.45465714] -> ?     0.00 
         [ 0.61296923 -0.55631212  0.99550312  1.28461716] -> ?     2.00 
         [-1.01607442  0.80311241 -1.27428354 -1.32421551] -> ?     0.00 

                                                    input  -> pred  des. 
                                         [5.1 3.5 1.4 0.2] -> ?     0.00 
                                         [4.4 3.2 1.3 0.2] -> ?     0.00 
                                         [4.8 3.  1.4 0.1] -> ?     0.00 
                                         [6.4 2.8 5.6 2.2] -> ?     2.00 
                                         [5.  3.4 1.5 0.2] -> ?     0.00 



In [18]:
from sklearn.neural_network import MLPClassifier

#
# Here's where you can change the number of hidden layers
# and number of neurons!
#
nn_classifier = MLPClassifier(hidden_layer_sizes=(6,7),  # 3 input -> 6 -> 7 -> 1 output
                    max_iter=500,      # how many times to train
                    activation="tanh", # the "activation function" input -> output
                    solver='sgd',      # the algorithm for optimizing weights
                    verbose=True,      # False to "mute" the training
                    shuffle=True,      # reshuffle the training epochs?
                    random_state=None, # set for reproduceability
                    learning_rate_init=.1,       # learning rate: % of error to backprop
                    learning_rate = 'adaptive')  # soften feedback as it converges

# documentation:
# scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html 
#     Try verbose / activation "relu" / other network sizes ...

print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
nn_classifier.fit(X_train_scaled, y_train_scaled)
print("\n++++++++++  TRAINING:   end  +++++++++++++++")
print(f"The analog prediction error (the loss) is {nn_classifier.loss_}")



++++++++++  TRAINING:  begin  +++++++++++++++


Iteration 1, loss = 1.22028668
Iteration 2, loss = 1.05884133
Iteration 3, loss = 0.90277548
Iteration 4, loss = 0.77298412
Iteration 5, loss = 0.67099173
Iteration 6, loss = 0.59664928
Iteration 7, loss = 0.54580306
Iteration 8, loss = 0.50979849
Iteration 9, loss = 0.48161161
Iteration 10, loss = 0.45818486
Iteration 11, loss = 0.43854263
Iteration 12, loss = 0.42176247
Iteration 13, loss = 0.40654668
Iteration 14, loss = 0.39175781
Iteration 15, loss = 0.37683378
Iteration 16, loss = 0.36172731
Iteration 17, loss = 0.34661114
Iteration 18, loss = 0.33164952
Iteration 19, loss = 0.31693372
Iteration 20, loss = 0.30251397
Iteration 21, loss = 0.28843280
Iteration 22, loss = 0.27471959
Iteration 23, loss = 0.26135882
Iteration 24, loss = 0.24826099
Iteration 25, loss = 0.23525326
Iteration 26, loss = 0.22209160
Iteration 27, loss = 0.20849216
Iteration 28, loss = 0.19418936
Iteration 29, loss = 0.17903695
Iteration 30, loss = 0.16315330

In [19]:
#
# how did it do on the testing data?
#

def ascii_table_for_classifier(Xsc,y,nn,scaler):
    """ a table including predictions using nn.predict """
    predictions = nn.predict(Xsc)            # all predictions
    prediction_probs = nn.predict_proba(Xsc) # all prediction probabilities
    Xpr = scaler.inverse_transform(Xsc)      # Xpr is the "X to print": unscaled data!
    # count correct
    num_correct = 0
    # printing
    print(f"{'input ':>28s} -> {'pred':^6s} {'des.':^6s}") 
    for i in range(len(y)):
        pred = predictions[i]
        pred_probs = prediction_probs[i,:]
        desired = y[i]
        if pred != desired: result = "  incorrect: " + str(pred_probs)
        else: result = "  correct"; num_correct += 1
        # Xpr = Xsc  # if you want to see the scaled versions
        print(f"{Xpr[i,0:4]!s:>28s} -> {pred:^6.0f} {desired:^6.0f} {result:^10s}") 
    print(f"\ncorrect predictions: {num_correct} out of {len(y)}")
    
#
# let's see how it did on the test data (also the training data!)
#
ascii_table_for_classifier(X_test_scaled,
                           y_test_scaled,
                           nn_classifier,
                           scaler)   


                      input  ->  pred   des. 
           [5.  3.4 1.6 0.4] ->   0      0      correct 
           [5.6 3.  4.5 1.5] ->   1      1      correct 
           [5.1 3.8 1.9 0.4] ->   0      0      correct 
           [6.1 3.  4.9 1.8] ->   2      2      correct 
           [5.5 2.6 4.4 1.2] ->   1      1      correct 
           [6.9 3.2 5.7 2.3] ->   2      2      correct 
           [6.  2.7 5.1 1.6] ->   2      1      incorrect: [1.99713845e-05 9.46095084e-03 9.90519078e-01]
           [4.8 3.4 1.6 0.2] ->   0      0      correct 
           [4.8 3.4 1.9 0.2] ->   0      0      correct 
           [6.7 3.1 4.4 1.4] ->   1      1      correct 
           [6.7 3.  5.  1.7] ->   2      1      incorrect: [0.00067016 0.47966322 0.51966663]
           [6.4 3.2 4.5 1.5] ->   1      1      correct 
           [5.6 2.5 3.9 1.1] ->   1      1      correct 
           [5.8 2.8 5.1 2.4] ->   2      2      correct 
           [6.8 2.8 4.8 1.4] ->   1      1      correct 
           [5

In [20]:
#
# We don't usually look inside the NNet, but we can: it's open-box modeling...
#
if True:  # do we want to see all of the parameters?
    nn = nn_classifier  # less to type?
    print("\n\n+++++ parameters, weights, etc. +++++\n")
    print(f"\nweights/coefficients:\n")
    for wts in nn.coefs_:
        print(wts)
    print(f"\nintercepts: {nn.intercepts_}")
    print(f"\nall parameters: {nn.get_params()}")



+++++ parameters, weights, etc. +++++


weights/coefficients:

[[ 0.71577514 -0.48344458  0.17730161 -0.35870988 -0.27866579  0.16619497]
 [-0.70299769  0.76693828 -0.64804603  0.27535037 -0.29619662 -0.79179112]
 [-0.09915524 -0.6149513   1.39178746  0.78250919  2.11679131  0.08053353]
 [ 0.2839601  -0.72383763  0.03618368  0.68088102  0.96304513 -0.32716529]]
[[ 0.21413275  0.40759952 -0.40754848 -0.6094538  -0.34888712 -0.64769912
  -0.01035517]
 [-1.42954781  0.76100632  1.39110104 -1.00552669  0.19150092  0.20295821
  -1.41788307]
 [ 1.0193069  -0.10470335 -0.0250311   0.47995134  0.28145519 -0.19405143
   0.58959419]
 [-0.8281488  -0.79860103 -0.15523871 -0.04235236  0.23887003 -0.19883116
  -0.46576591]
 [-0.02493792 -1.09535164 -1.20028606 -0.4926598   1.89966135 -1.79819018
   0.62607378]
 [-0.44712677  0.12417221 -1.09123117  0.2956209  -0.42985191  0.40451299
   0.30032667]]
[[-1.15605518  1.02649306  0.365404  ]
 [ 1.16823532  0.0542765  -1.74412414]
 [ 1.48290666  0.7652

In [21]:
#
# we have a predictive model!  Let's try it out...
#

def make_prediction( Features, nn, scaler ):
    """ uses nn for predictions """
    print("input features are", Features)
    #  we make sure Features has the right shape (list-of-lists)
    row = np.array( [Features] )  # makes an array-row
    row = scaler.transform(row)   # scale according to scaler
    print("nn.predict_proba == ", nn.predict_proba(row))   # probabilities of each
    prediction = nn.predict(row)  # max!
    return prediction
    
# our features -- note that the inputs don't have to be bits!
Features = [ 6.7, 3.1, 5.6, 2.4 ]      # whatever we'd like to test
prediction = make_prediction(Features, nn_classifier, scaler)
print(f"prediction: {prediction}")     # takes the max (nice to see them all!)

input features are [6.7, 3.1, 5.6, 2.4]
nn.predict_proba ==  [[2.43335004e-06 2.08463519e-04 9.99789103e-01]]
prediction: [2.]


In [22]:
print(COL_INDEX)
print(COLUMNS)

# Let's first predict sepal length ('sepallen', column index 0)

{'sepallen': 0, 'sepalwid': 1, 'petallen': 2, 'petalwid': 3, 'irisnum': 4}
Index(['sepallen', 'sepalwid', 'petallen', 'petalwid', 'irisnum'], dtype='object')


In [23]:
#
# Here we set up for a regression model that will predict 'sepallen'  (column index 0)  using
#

#   sepal width   'sepalwid' (column index 1)
#   petal length  'petallen' (column index 2)
#   petal width   'petalwid' (column index 3)
#     and
#   species       'irisnum'  (column index 4)

print("+++ Start of data-assembly for feature-regression! +++\n")
# construct the correct X_all from the columns we want
# we use np.concatenate to combine parts of the dataset to get all-except-column 0:
X_all = np.concatenate( (A[:,0:0], A[:,1:]),axis=1)  # columns 1, 2, 3, and 4

# if we wanted all-except-column 1:   X_all = np.concatenate( (A[:,0:1], A[:,2:]),axis=1)  # columns 0, 2, 3, and 4
# if we wanted all-except-column 2:   X_all = np.concatenate( (A[:,0:2], A[:,3:]),axis=1)  # columns 0, 1, 3, and 4
# if we wanted all-except-column 3:   X_all = np.concatenate( (A[:,0:3], A[:,4:]),axis=1)  # columns 0, 1, 2, and 4
# if we wanted all-except-column 4:   X_all = np.concatenate( (A[:,0:4], A[:,5:]),axis=1)  # columns 0, 1, 2, and 3



y_all = A[:,0]             # y (labels) ... is all of column 0, sepallen (sepal length)  Re-index, as needed...
print(f"y_all is \n {y_all}") 
print(f"X_all (just features: first few rows) is \n {X_all[:5,:]}")


+++ Start of data-assembly for feature-regression! +++

y_all is 
 [4.6 4.3 5.  5.8 4.4 4.4 4.5 4.7 5.  5.4 5.5 4.4 4.6 4.6 4.8 4.8 4.9 5.
 5.  5.1 5.1 5.2 5.5 4.6 4.9 4.9 4.9 5.  5.1 5.1 5.1 5.2 5.3 5.4 5.7 4.7
 4.8 5.  5.  5.  5.1 5.1 5.4 5.4 5.7 4.8 5.1 7.  4.9 5.  5.  5.7 5.6 5.5
 5.5 5.2 5.6 5.8 5.5 5.5 5.8 6.  6.1 5.6 5.8 5.6 5.7 5.9 6.4 5.5 6.3 6.6
 6.7 5.4 5.6 5.7 6.  6.  6.2 6.4 6.1 6.5 6.6 6.1 6.1 6.3 6.7 5.9 6.8 6.3
 6.9 6.7 6.  4.9 6.  6.2 5.6 6.1 6.3 5.7 6.  6.3 5.8 5.8 5.9 6.3 6.5 6.9
 6.5 6.7 6.4 6.4 6.2 6.9 6.4 6.5 6.8 6.1 6.3 6.3 6.4 6.4 6.7 6.7 6.7 6.9
 6.5 6.7 7.2 6.8 7.1 7.2 7.2 7.4 7.7 7.3 7.9 7.6 7.7 7.7 7.7]
X_all (just features: first few rows) is 
 [[3.6 1.  0.2 0. ]
 [3.  1.1 0.1 0. ]
 [3.2 1.2 0.2 0. ]
 [4.  1.2 0.2 0. ]
 [3.  1.3 0.2 0. ]]


In [24]:
#
# we scramble the data, to give a different TRAIN/TEST split each time...
# 
indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_all = X_all[indices]              # we apply the _same_ permutation to each!
y_all = y_all[indices]              # again...
print("label-_values_\n",y_all)
print("\nfeatures (a few)\n", X_all[:5,:])

label-_values_
 [5.7 5.5 6.1 7.7 6.4 6.3 6.2 6.1 5.6 5.1 6.6 5.7 5.9 6.7 5.  5.2 6.9 5.1
 5.3 6.7 7.7 6.3 5.5 4.3 5.  5.5 5.  5.7 5.6 6.1 7.2 6.5 5.8 6.2 6.5 4.5
 6.7 5.4 4.6 6.  6.7 5.8 5.5 7.6 7.7 6.  5.4 6.7 5.9 6.8 7.9 4.8 6.3 5.9
 5.7 4.8 5.1 6.7 6.4 5.6 7.3 5.5 6.5 6.8 6.3 6.1 5.6 4.8 6.1 6.6 4.9 6.1
 5.  6.9 6.8 4.6 4.4 4.7 6.7 5.6 5.5 5.6 6.3 5.  5.  4.7 7.2 5.8 5.8 6.4
 7.  6.3 7.1 5.2 6.  6.  5.  6.3 6.  4.9 5.1 6.  5.7 6.4 7.7 4.9 5.  5.7
 4.4 7.4 5.8 4.9 5.5 5.2 5.8 6.4 5.4 5.4 6.5 6.3 6.4 7.2 6.5 6.9 4.6 5.1
 4.9 6.7 5.  4.6 6.2 4.4 4.9 5.4 5.  4.8 5.1 6.4 5.1 6.9 5.1]

features (a few)
 [[3.8 1.7 0.3 0. ]
 [4.2 1.4 0.2 0. ]
 [3.  4.6 1.4 1. ]
 [2.8 6.7 2.  2. ]
 [2.8 5.6 2.1 2. ]]


In [25]:
#
# We next separate into test data and training data ... 
#    + We will train on the training data...
#    + We will _not_ look at the testing data to build the model
#
# Then, afterward, we will test on the testing data -- and see how well we do!
#

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2)

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows\n" )

print(f"Held-out data... (testing data: {len(y_test)})")
print(f"y_test: {y_test}\n")
print(f"X_test (few rows): {X_test[0:5,:]}")  # 5 rows
print()
print(f"Data used for modeling... (training data: {len(y_train)})")
print(f"y_train: {y_train}\n")
print(f"X_train (few rows): {X_train[0:5,:]}")  # 5 rows

training with 112 rows;  testing with 29 rows

Held-out data... (testing data: 29)
y_test: [6.5 6.  6.3 6.7 6.4 6.  4.6 6.  6.3 6.5 6.1 5.5 6.  7.7 6.8 5.  4.9 5.
 7.3 7.9 7.4 7.2 5.9 6.4 5.1 7.7 5.  6.8 5.1]

X_test (few rows): [[3.  5.5 1.8 2. ]
 [2.2 5.  1.5 2. ]
 [2.5 4.9 1.5 1. ]
 [3.1 5.6 2.4 2. ]
 [2.8 5.6 2.2 2. ]]

Data used for modeling... (training data: 112)
y_train: [6.1 5.6 4.8 4.4 6.1 6.  5.7 6.2 5.5 6.4 5.6 5.8 4.4 5.9 5.2 4.9 6.1 4.7
 5.8 5.4 6.4 5.1 6.3 5.7 4.4 6.7 4.6 4.3 6.6 5.8 5.6 6.2 6.4 5.2 6.3 4.8
 5.8 6.9 6.7 5.  6.5 5.7 5.6 7.1 4.9 5.8 5.6 4.6 7.2 5.5 5.2 6.7 6.9 7.7
 7.7 4.5 4.8 5.1 5.7 5.4 6.3 6.6 5.4 4.7 5.5 6.9 6.7 5.1 5.5 5.7 5.5 4.6
 4.9 7.2 6.5 7.  6.3 6.5 6.8 5.  6.1 5.3 5.  6.7 5.4 5.6 6.3 5.  6.3 6.2
 5.8 5.1 6.4 6.  4.9 5.7 5.5 6.7 5.  4.9 5.4 6.4 5.1 5.  5.  6.7 4.8 6.1
 7.6 5.1 5.9 6.9]

X_train (few rows): [[2.6 5.6 1.4 2. ]
 [3.  4.5 1.5 1. ]
 [3.  1.4 0.1 0. ]
 [2.9 1.4 0.2 0. ]
 [2.8 4.  1.3 1. ]]


In [26]:
#
# for NNets, it's important to keep the feature values near 0, say -1. to 1. or so
#    This is done through the "StandardScaler" in scikit-learn
#
from sklearn.preprocessing import StandardScaler

USE_SCALER = True   # this variable is important! It tracks if we need to use the scaler...

# we "train the scaler"  (computes the mean and standard deviation)
if USE_SCALER == True:
    scaler = StandardScaler()
    scaler.fit(X_train)  # Scale with the training data! ave becomes 0; stdev becomes 1
else:
    # this one does no scaling!  We still create it to be consistent:
    scaler = StandardScaler(copy=True, with_mean=False, with_std=False) # no scaling
    scaler.fit(X_train)  # still need to fit, though it does not change...

scaler   # is now defined and ready to use...

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Here are our scaled training and testing sets:

X_train_scaled = scaler.transform(X_train) # scale!
X_test_scaled = scaler.transform(X_test) # scale!

y_train_scaled = y_train  # the predicted/desired labels are not scaled
y_test_scaled = y_test  # not using the scaler

# reused from above - seeing the scaled data 
ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],None)

# reused from above - seeing the unscaled data (inverting the scaler)
ascii_table(X_train_scaled[0:5,:],y_train_scaled[0:5],scaler)

                                                    input  -> pred  des. 
         [-1.05857312  1.14787329  0.32751069  1.27847857] -> ?     6.10 
         [-0.15006592  0.51085532  0.45851497  0.05463584] -> ?     5.60 
         [-0.15006592 -1.28437714 -1.37554491 -1.1692069 ] -> ?     4.80 
         [-0.37719272 -1.28437714 -1.24454064 -1.1692069 ] -> ?     4.40 
         [-0.60431952  0.2213017   0.19650642  0.05463584] -> ?     6.10 

                                                    input  -> pred  des. 
                                         [2.6 5.6 1.4 2. ] -> ?     6.10 
                                         [3.  4.5 1.5 1. ] -> ?     5.60 
[3.00000000e+00 1.40000000e+00 1.00000000e-01 1.11022302e-16] -> ?     4.80 
[2.90000000e+00 1.40000000e+00 2.00000000e-01 1.11022302e-16] -> ?     4.40 
                                         [2.8 4.  1.3 1. ] -> ?     6.10 



In [27]:
#
# MLPRegressor predicts _floating-point_ outputs
#

from sklearn.neural_network import MLPRegressor

nn_regressor = MLPRegressor(hidden_layer_sizes=(6,7), 
                    max_iter=200,          # how many training epochs
                    activation="tanh",     # the activation function
                    solver='sgd',          # the optimizer
                    verbose=True,          # do we want to watch as it trains?
                    shuffle=True,          # shuffle each epoch?
                    random_state=None,     # use for reproducibility
                    learning_rate_init=.1, # how much of each error to back-propagate
                    learning_rate = 'adaptive')  # how to handle the learning_rate

print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
nn_regressor.fit(X_train_scaled, y_train_scaled)
print("++++++++++  TRAINING:   end  +++++++++++++++")

print(f"The (squared) prediction error (the loss) is {nn_regressor.loss_}")
print(f"And, its square root: {nn_regressor.loss_ ** 0.5}")



++++++++++  TRAINING:  begin  +++++++++++++++


Iteration 1, loss = 21.55772744
Iteration 2, loss = 8.95268086
Iteration 3, loss = 0.94745943
Iteration 4, loss = 1.62428017
Iteration 5, loss = 1.26387867
Iteration 6, loss = 0.28175406
Iteration 7, loss = 0.25895612
Iteration 8, loss = 0.22341759
Iteration 9, loss = 0.17792478
Iteration 10, loss = 0.18699243
Iteration 11, loss = 0.19577202
Iteration 12, loss = 0.19416643
Iteration 13, loss = 0.18489210
Iteration 14, loss = 0.17491059
Iteration 15, loss = 0.16945270
Iteration 16, loss = 0.16584219
Iteration 17, loss = 0.16165187
Iteration 18, loss = 0.15670549
Iteration 19, loss = 0.15108041
Iteration 20, loss = 0.14441591
Iteration 21, loss = 0.13649299
Iteration 22, loss = 0.12754106
Iteration 23, loss = 0.11820768
Iteration 24, loss = 0.10943492
Iteration 25, loss = 0.10223770
Iteration 26, loss = 0.09733784
Iteration 27, loss = 0.09479870
Iteration 28, loss = 0.09394275
Iteration 29, loss = 0.09367415
Iteration 30, loss = 0.0930014

c:\Users\chung\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [67]:
#
# how did it do? Try out the TEST data...
#

def ascii_table_for_regressor(Xsc,y,nn,scaler):
    """ a table including predictions using nn.predict """
    predictions = nn.predict(Xsc) # all predictions
    Xpr = scaler.inverse_transform(Xsc)  # Xpr is the "X to print": unscaled data!
    # measure error
    error = 0.0
    # printing
    print(f"{'input ':>28s} ->  {'pred':^6s}  {'des.':^6s}  {'absdiff':^10s}") 
    for i in range(len(y)):
        pred = predictions[i]
        desired = y[i]
        result = abs(desired - pred)
        error += result
        # Xpr = Xsc   # if you'd like to see the scaled values
        print(f"{Xpr[i,0:4]!s:>28s} ->  {pred:<+6.3f}  {desired:<+6.3f}  {result:^10.3f}") 

    print("\n" + "+++++   +++++      +++++   +++++   ")
    print(f"average abs error: {error/len(y)}")
    print("+++++   +++++      +++++   +++++   ")
    
#
# let's see how it did on the test data (also the training data!)
#
ascii_table_for_regressor(X_test_scaled,
                          y_test_scaled,
                          nn_regressor,
                          scaler)   # this is our own f'n, above


                      input  ->   pred    des.    absdiff  
[5.20000000e+00 3.50000000e+00 1.50000000e+00 1.11022302e-16] ->  +0.248  +0.200    0.048   
           [6.3 2.5 5.  2. ] ->  +1.691  +1.900    0.209   
           [6.4 2.9 4.3 1. ] ->  +1.397  +1.300    0.097   
           [6.7 3.1 4.7 1. ] ->  +1.506  +1.500    0.006   
           [6.2 3.4 5.4 2. ] ->  +2.151  +2.300    0.149   
           [6.4 3.2 5.3 2. ] ->  +2.160  +2.300    0.140   
           [7.1 3.  5.9 2. ] ->  +2.060  +2.100    0.040   
           [5.9 3.  5.1 2. ] ->  +2.090  +1.800    0.290   
           [6.3 3.3 4.7 1. ] ->  +1.558  +1.600    0.042   
[4.80000000e+00 3.00000000e+00 1.40000000e+00 1.11022302e-16] ->  +0.154  +0.300    0.146   
           [5.7 2.6 3.5 1. ] ->  +1.078  +1.000    0.078   
[5.70000000e+00 3.80000000e+00 1.70000000e+00 1.11022302e-16] ->  +0.260  +0.300    0.040   
           [6.5 3.2 5.1 2. ] ->  +2.133  +2.000    0.133   
           [6.  3.  4.8 2. ] ->  +2.060  +1.800    0.260   
 

In [68]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

print("+++ Start of data-assembly for feature-regression! +++\n")
# construct the correct X_all from the columns we want
# we use np.concatenate to combine parts of the dataset to get all-except-column 0:

for f in range(4):
    X_all = np.concatenate( (A[:,0:f], A[:,1+f:]),axis=1) 
    y_all = A[:,f+1]             # y (labels) ... is all of column 0, sepallen (sepal length)  Re-index, as needed...
    # 
   
    # if we wanted all-except-column 1:   X_all = np.concatenate( (A[:,0:1], A[:,2:]),axis=1)  # columns 0, 2, 3, and 4
    # if we wanted all-except-column 2:   X_all = np.concatenate( (A[:,0:2], A[:,3:]),axis=1)  # columns 0, 1, 3, and 4
    # if we wanted all-except-column 3:   X_all = np.concatenate( (A[:,0:3], A[:,4:]),axis=1)  # columns 0, 1, 2, and 4
    # if we wanted all-except-column 4:   X_all = np.concatenate( (A[:,0:4], A[:,5:]),axis=1)  # columns 0, 1, 2, and 3
    # slicing is forgiving...

    
    

    # we scramble the data, to give a different TRAIN/TEST split each time...
    # 
    indices = np.random.permutation(len(y_all))  # indices is a permutation-list

    # we scramble both X and y, necessarily with the same permutation
    X_all = X_all[indices]              # we apply the _same_ permutation to each!
    y_all = y_all[indices]              # again...


    X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2)

    # Scaling Part...

    USE_SCALER = True   # this variable is important! It tracks if we need to use the scaler...

    # we "train the scaler"  (computes the mean and standard deviation)
    if USE_SCALER == True:
        scaler = StandardScaler()
        scaler.fit(X_train)  # Scale with the training data! ave becomes 0; stdev becomes 1
    else:
        # this one does no scaling!  We still create it to be consistent:
        scaler = StandardScaler(copy=True, with_mean=False, with_std=False) # no scaling
        scaler.fit(X_train)  # still need to fit, though it does not change...

    # ++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # Here are our scaled training and testing sets:

    X_train_scaled = scaler.transform(X_train) # scale!
    X_test_scaled = scaler.transform(X_test) # scale!

    y_train_scaled = y_train  # the predicted/desired labels are not scaled
    y_test_scaled = y_test  # not using the scaler

    #
    # MLPRegressor predicts _floating-point_ outputs
    #


    nn_regressor = MLPRegressor(hidden_layer_sizes=(6,7), 
                        max_iter=200,          # how many training epochs
                        activation="tanh",     # the activation function
                        solver='sgd',          # the optimizer
                        verbose=False,          # do we want to watch as it trains?
                        shuffle=True,          # shuffle each epoch?
                        random_state=None,     # use for reproducibility
                        learning_rate_init=.1, # how much of each error to back-propagate
                        learning_rate = 'adaptive')  # how to handle the learning_rate

    # print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
    nn_regressor.fit(X_train_scaled, y_train_scaled)
    # print("++++++++++  TRAINING:   end  +++++++++++++++")

    # print(f"The (squared) prediction error (the loss) is {nn_regressor.loss_}")
    # print(f"And, its square root: {nn_regressor.loss_ ** 0.5}")
    # print()
    # print()
#
# how did it do? Try out the TEST data...
#
    predictions = nn_regressor.predict(X_test_scaled) # all predictions
    Xpr = scaler.inverse_transform(X_test_scaled)  # Xpr is the "X to print": unscaled data!
    # measure error
    error = 0.0
    # printing
    for i in range(len(y_test_scaled)):
        pred = predictions[i]
        desired = y_test_scaled[i]
        result = abs(desired - pred)
        error += result
        # Xpr = Xsc   # if you'd like to see the scaled values

    print(f"average abs error: {error/len(y_test_scaled)} for iteration {f}")





    

+++ Start of data-assembly for feature-regression! +++

average abs error: 0.2523899376242552 for iteration 0
average abs error: 0.20686995917477938 for iteration 1
average abs error: 0.33074590490155203 for iteration 2
average abs error: 0.14797933053053164 for iteration 3


c:\Users\chung\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
